## PART 1 — Data Preprocessing

**Task 1: Load & Understand Dataset**
1. Load the dataset using Pandas.
2. Print:
   - Dataset shape
   - Column names
   - First 5 rows
   - Other essential Details
3. Identify text column(s) used for recommendations.

In [27]:
import pandas as pd

In [28]:
df = pd.read_csv('tmdb_5000_movies.csv')

In [29]:
df.head()

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2009-12-10,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2007-05-19,961000000,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.sonypictures.com/movies/spectre/,206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bond’s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...","[{""iso_3166_1"": ""GB"", ""name"": ""United Kingdom""...",2015-10-26,880674609,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466
3,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",http://www.thedarkknightrises.com/,49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-07-16,1084939099,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106
4,260000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://movies.disney.com/john-carter,49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-03-07,284139100,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124

In [30]:
df.columns

Index(['budget', 'genres', 'homepage', 'id', 'keywords', 'original_language',
       'original_title', 'overview', 'popularity', 'production_companies',
       'production_countries', 'release_date', 'revenue', 'runtime',
       'spoken_languages', 'status', 'tagline', 'title', 'vote_average',
       'vote_count'],
      dtype='str')

In [31]:
df[['overview', 'genres', 'keywords', 'title', 'tagline']]

,overview,genres,keywords,title,tagline
0,"In the 22nd century, a paraplegic Marine is di...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",Avatar,Enter the World of Pandora.
1,"Captain Barbossa, long believed to be dead, ha...","[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...","[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",Pirates of the Caribbean: At World's End,"At the end of the world, the adventure begins."
2,A cryptic message from Bond’s past sends him o...,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",Spectre,A Plan No One Escapes
3,Following the death of District Attorney Harve...,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...","[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",The Dark Knight Rises,The Legend Ends
4,"John Carter is a war-weary, former military ca...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",John Carter,"Lost in our world, found in another."
...,...,...,...,...,...
4798,El Mariachi just wants to play his guitar and ...,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...","[{""id"": 5616, ""name"": ""united states\u2013mexi...",El Mariachi,"He didn't come looking for trouble, but troubl..."
4799,A newlywed couple's honeymoon is upended by th...,"[{""id"": 35, ""name"": ""Comedy""}, {""id"": 10749, ""...",[],Newlyweds,A newlywed couple's honeymoon is upended by th...
4800,"""Signed, Sealed, Delivered"" introduces a dedic...","[{""id"": 35, ""name"": ""Comedy""}, {""id"": 18, ""nam...","[{""id"": 248, ""name"": ""date""}, {""id"": 699, ""nam...","Signed, Sealed, Delivered",NaN
4801,When ambitious New York attorney Sam is sent t...,[],[],Shanghai Calling,A New Yorker in Shanghai
4802,Ever since the second grade when he first saw ...,"[{""id"": 99, ""name"": ""Documentary""}]","[{""id"": 1523, ""name"": ""obsession""}, {""id"": 224...",My Date with Drew,NaN

In [32]:
df = df[['overview', 'genres', 'keywords', 'title', 'tagline']]

In [33]:
df['genres'][0]

'[{"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"}, {"id": 14, "name": "Fantasy"}, {"id": 878, "name": "Science Fiction"}]'

In [34]:
import json

In [35]:
g = json.loads(df['genres'][0])
g

[{'id': 28, 'name': 'Action'},
 {'id': 12, 'name': 'Adventure'},
 {'id': 14, 'name': 'Fantasy'},
 {'id': 878, 'name': 'Science Fiction'}]

In [36]:
# preprocessing genres and keywords
def preprocess_genres(genres):
    if pd.isna(genres) or genres == '[]' or genres == '':
        return ''
    genres_json = json.loads(genres)
    genres_list = [genre['name'] for genre in genres_json]
    return ' '.join(genres_list)

def preprocess_keywords(keywords):
    if pd.isna(keywords) or keywords == '[]' or keywords == '':
        return ''
    keywords_json = json.loads(keywords)
    keywords_list = [keyword['name'] for keyword in keywords_json]
    return ' '.join(keywords_list)

df['genres'] = df['genres'].apply(preprocess_genres)
df['keywords'] = df['keywords'].apply(preprocess_keywords)
df.head()
df.dropna(inplace=True)

In [37]:
df.dropna(inplace=True)
df.head()

,overview,genres,keywords,title,tagline
0,"In the 22nd century, a paraplegic Marine is di...",Action Adventure Fantasy Science Fiction,culture clash future space war space colony so...,Avatar,Enter the World of Pandora.
1,"Captain Barbossa, long believed to be dead, ha...",Adventure Fantasy Action,ocean drug abuse exotic island east india trad...,Pirates of the Caribbean: At World's End,"At the end of the world, the adventure begins."
2,A cryptic message from Bond’s past sends him o...,Action Adventure Crime,spy based on novel secret agent sequel mi6 bri...,Spectre,A Plan No One Escapes
3,Following the death of District Attorney Harve...,Action Crime Drama Thriller,dc comics crime fighter terrorist secret ident...,The Dark Knight Rises,The Legend Ends
4,"John Carter is a war-weary, former military ca...",Action Adventure Science Fiction,based on novel mars medallion space travel pri...,John Carter,"Lost in our world, found in another."

In [38]:
df['movie_blob'] = df['overview'] \
    + ' ' + df['genres'] \
    + ' ' + df['keywords'] \
    + ' ' + df['tagline'] \
    + ' ' + df['title']
data = df[['movie_blob', 'title']]
data.head()

,movie_blob,title
0,"In the 22nd century, a paraplegic Marine is di...",Avatar
1,"Captain Barbossa, long believed to be dead, ha...",Pirates of the Caribbean: At World's End
2,A cryptic message from Bond’s past sends him o...,Spectre
3,Following the death of District Attorney Harve...,The Dark Knight Rises
4,"John Carter is a war-weary, former military ca...",John Carter

**Task 2: Text Preprocessing for Recommendation**
Apply the following steps on the text column:
1. Convert text to lowercase
2. Remove punctuation and special characters
3. Remove stopwords
4. Handle missing values (replace with empty string)

Store cleaned text in a new column: clean_text.

In [39]:
import nltk

In [40]:
import re
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer

In [41]:
stop_words = set(stopwords.words('english'))
wordnet_lemmatizer = WordNetLemmatizer()

In [42]:
def nlp_preprocess(text):
    # lowercasing
    text = text.lower()
    # noise removal
    # remove urls
    text = re.sub(r'https?://(www\.)?[-a-zA-Z0-9@:%._\+~#=]{2,256}\.[a-z]{2,4}\b([-a-zA-Z0-9@:%_\+.~#?&//=]*)', '', text)
    # remove email addresses
    text = re.sub(r'[\w\.-]+@[\w\.-]+', '', text)
    # remove html tags
    text = re.sub(r'<.*?>', '', text)
    # remove special characters & emojis
    text = re.sub(r'[^a-zA-Z0-9\s]', '', text)
    # remove extra spaces
    text = re.sub(r'\s+', ' ', text)
    # remove numbers
    text = re.sub(r'\d', '', text)
    # stopword removal
    text = ' '.join([word for word in text.split() if word not in stop_words])
    # tokenization
    tokens = word_tokenize(text)
    # lemmatization
    tokens = [wordnet_lemmatizer.lemmatize(word) for word in tokens]
    # join tokens back into text
    return ' '.join(tokens)

In [43]:
data['clean_text'] = data['movie_blob'].apply(nlp_preprocess)
data.head()

,movie_blob,title,clean_text
0,"In the 22nd century, a paraplegic Marine is di...",Avatar,nd century paraplegic marine dispatched moon p...
1,"Captain Barbossa, long believed to be dead, ha...",Pirates of the Caribbean: At World's End,captain barbossa long believed dead come back ...
2,A cryptic message from Bond’s past sends him o...,Spectre,cryptic message bond past sends trail uncover ...
3,Following the death of District Attorney Harve...,The Dark Knight Rises,following death district attorney harvey dent ...
4,"John Carter is a war-weary, former military ca...",John Carter,john carter warweary former military captain w...

## PART 2 — Text Vectorization

**Task 3: Vectorization using TF-IDF**

1. Use TfidfVectorizer() to convert text into vectors.
2. Set reasonable parameters:
   - max_features
   - ngram_range
3. Display:
   - Shape of TF-IDF matrix

In [44]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [45]:
vectorizer = TfidfVectorizer(max_features=15000, ngram_range=(1, 3))

In [46]:
# Use TfidfVectorizer() to convert text into vectors.
tf_idf_matrix = vectorizer.fit_transform(data['clean_text'])
tf_idf_matrix.shape

(3959, 15000)

**Task 4: Similarity Computation**

1. Compute cosine similarity between all items.
2. Store similarity matrix.
3. Explain briefly why cosine similarity is used.

In [47]:
from sklearn.metrics.pairwise import cosine_similarity
import pickle

# Compute cosine similarity between all items
similarity_matrix = cosine_similarity(tf_idf_matrix)

# Store similarity matrix
with open('similarity_matrix.pkl', 'wb') as f:
    pickle.dump(similarity_matrix, f)

# Load similarity matrix
with open('similarity_matrix.pkl', 'rb') as f:
    similarity_matrix = pickle.load(f)

In [48]:
similarity_matrix.shape

(3959, 3959)

In [50]:
similarity_matrix

array([[1.        , 0.0278861 , 0.01734386, ..., 0.00149318, 0.00292214,
        0.00276155],
       [0.0278861 , 1.        , 0.0161056 , ..., 0.00953689, 0.        ,
        0.01313887],
       [0.01734386, 0.0161056 , 1.        , ..., 0.01248583, 0.        ,
        0.        ],
       ...,
       [0.00149318, 0.00953689, 0.01248583, ..., 1.        , 0.        ,
        0.00251274],
       [0.00292214, 0.        , 0.        , ..., 0.        , 1.        ,
        0.00331287],
       [0.00276155, 0.01313887, 0.        , ..., 0.00251274, 0.00331287,
        1.        ]], shape=(3959, 3959))

## PART 3 — Recommendation Logic

**Task 5: Build Recommendation Function**
Create a function:

```
def recommend(item_name, top_n=5):
    # returns top N similar items
```

Function should:

1. Find index of the selected item
2. Compute similarity scores
3. Sort and return top recommendations

Test with at least 3 different items.

In [59]:
def recommend(item_name, top_n=5):
    # returns top N similar items
    item_index = data[data['title'] == item_name].index[0]
    similarity_scores = list(enumerate(similarity_matrix[item_index]))
    similarity_scores = sorted(similarity_scores, key=lambda x: x[1], reverse=True)
    top_n_indices = [i[0] for i in similarity_scores[1:top_n+1]]
    return data['title'].iloc[top_n_indices]

In [ ]:
print(recommend('The Dark Knight Rises'))

65      The Dark Knight
299      Batman Forever
119       Batman Begins
428      Batman Returns
1359             Batman
Name: title, dtype: str

## PART 4 — Simple App Interface

**Task 6: Build UI using Streamlit**

1. Create a simple interface:
   - Dropdown to select item
   - Button to generate recommendations
2. Display recommended items clearly.

You may use:
Streamlit (preferred)


## PART 5 — Version Control with Git & GitHub

---

**Task 7: Git & GitHub Setup**

1. Initialize a Git repository.
2. Create a GitHub repository.
3. Push your project code to GitHub.

Repository must include:

- app.py
- requirements.txt
- README.md

---

## PART 6 — Deployment on Render

**Task 8: Deploy Application on Render**

1. Create a Render account.
2. Connect Render with GitHub.
3. Select your repository.
4. Configure:
   - Build command
   - Start command
5. Deploy the application.

**Task 9: Final Validation**

1. Test deployed app link.
2. Ensure recommendations work correctly.
3. Include deployed URL in submission.

# github repo -> https://github.com/aroy1856/movie-recomended-system/tree/main
# deployed app -> https://movie-recomended-system-n06e.onrender.com/