# Pandas Assignment

Working with a small employee dataframe — filter, group, sort, save to csv.

In [13]:
import pandas as pd

## 1. Create the DataFrame

Then peek at the data, get Age/Salary stats, and avg salary for HR.

In [14]:
data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'Diana', 'Eve'],
    'Age': [24, 27, 22, 32, 29],
    'Department': ['HR', 'Finance', 'IT', 'Marketing', 'HR'],
    'Salary': [45000, 54000, 50000, 62000, 47000]
}
df = pd.DataFrame(data)
df

      Name  Age Department  Salary
0    Alice   24         HR   45000
1      Bob   27    Finance   54000
2  Charlie   22         IT   50000
3    Diana   32  Marketing   62000
4      Eve   29         HR   47000

In [15]:
# first 5 rows (we only have 5 anyway)
df.head()

      Name  Age Department  Salary
0    Alice   24         HR   45000
1      Bob   27    Finance   54000
2  Charlie   22         IT   50000
3    Diana   32  Marketing   62000
4      Eve   29         HR   47000

In [16]:
# statistics of Age and Salary
df[['Age', 'Salary']].describe()

             Age        Salary
count   5.000000      5.000000
mean   26.800000  51600.000000
std     3.962323   6730.527468
min    22.000000  45000.000000
25%    24.000000  47000.000000
50%    27.000000  50000.000000
75%    29.000000  54000.000000
max    32.000000  62000.000000

In [17]:
hr = df[df['Department'] == 'HR']
print("avg HR salary:", hr['Salary'].mean())

avg HR salary: 46000.0

## 2. Bonus column

10% of salary.

In [18]:
df['Bonus'] = df['Salary'] * 0.1
df

      Name  Age Department  Salary   Bonus
0    Alice   24         HR   45000  4500.0
1      Bob   27    Finance   54000  5400.0
2  Charlie   22         IT   50000  5000.0
3    Diana   32  Marketing   62000  6200.0
4      Eve   29         HR   47000  4700.0

## 3. Filter by age

Only people between 25 and 30 (inclusive).

In [19]:
df[(df['Age'] >= 25) & (df['Age'] <= 30)]

  Name  Age Department  Salary   Bonus
1  Bob   27    Finance   54000  5400.0
4  Eve   29         HR   47000  4700.0

## 4. Average salary by department

In [20]:
df.groupby('Department')['Salary'].mean()

Department
Finance      54000.0
HR           46000.0
IT           50000.0
Marketing    62000.0
Name: Salary, dtype: float64

## 5. Sort by salary + save CSV

Ascending order, then write to employee_data.csv.

In [21]:
# ascending as per assignment
sorted_df = df.sort_values(by='Salary', ascending=True)
sorted_df.to_csv('employee_data.csv', index=False)
sorted_df

      Name  Age Department  Salary   Bonus
0    Alice   24         HR   45000  4500.0
4      Eve   29         HR   47000  4700.0
2  Charlie   22         IT   50000  5000.0
1      Bob   27    Finance   54000  5400.0
3    Diana   32  Marketing   62000  6200.0